nome = input('Digite seu nome completo: ')
nomeMA = nome.upper()
print(f'O nome convertido em letras maiúsculas será: \033[31m{nomeMA}\033[m')
nomeMI = nome.lower()
print(f'O nome convertido em letras minúsculas será: \033[32m{nomeMI}\033[m')
nomeSP = nome.replace(' ', '')
print(f'O nome tem ao todo: \033[33m{len(nomeSP)}\033[m letras')
nomePR = nome.split()
print(f'Seu primeiro nome tem: \033[34m{len(nomePR[0])}\033[m letras')
#Correto!